package com.liangjt.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-11T01:25:09.185+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "HelloWorld", 
                  wsdlLocation = "http://localhost:8080/cxf_spring/liangjt/webService?wsdl",
                  targetNamespace = "http://Impl.webService.liangjt.com/") 
public class HelloWorld extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Impl.webService.liangjt.com/", "HelloWorld");
    public final static QName HelloWorldWsPort = new QName("http://Impl.webService.liangjt.com/", "HelloWorldWsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf_spring/liangjt/webService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf_spring/liangjt/webService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorld(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorld(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorld() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWorld(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorld(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorld(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWsPort")
    public com.liangjt.webservice.HelloWorld getHelloWorldWsPort() {
        return super.getPort(HelloWorldWsPort, com.liangjt.webservice.HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWsPort")
    public com.liangjt.webservice.HelloWorld getHelloWorldWsPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldWsPort, com.liangjt.webservice.HelloWorld.class, features);
    }

}
